# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.srcs/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0.xci
# IP: The module: 'zynq_axi_gpio_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.gen/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.gen/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.gen/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.srcs/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0.xci
# IP: The module: 'zynq_axi_gpio_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.gen/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.gen/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.gen/sources_1/bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_gpio_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
