# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Zedboard-Master.xdc

# Block Designs: bd/zynq_axi_gpio/zynq_axi_gpio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio || ORIG_REF_NAME==zynq_axi_gpio} -quiet] -quiet

# IP: bd/zynq_axi_gpio/ip/zynq_axi_gpio_processing_system7_0_0/zynq_axi_gpio_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_processing_system7_0_0 || ORIG_REF_NAME==zynq_axi_gpio_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_axi_gpio/ip/zynq_axi_gpio_top_0_0/zynq_axi_gpio_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_top_0_0 || ORIG_REF_NAME==zynq_axi_gpio_top_0_0} -quiet] -quiet

# IP: bd/zynq_axi_gpio/ip/zynq_axi_gpio_axi_gpio_0_0/zynq_axi_gpio_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_axi_gpio_0_0 || ORIG_REF_NAME==zynq_axi_gpio_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_axi_gpio/ip/zynq_axi_gpio_axi_smc_0/zynq_axi_gpio_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_axi_smc_0 || ORIG_REF_NAME==zynq_axi_gpio_axi_smc_0} -quiet] -quiet

# IP: bd/zynq_axi_gpio/ip/zynq_axi_gpio_rst_ps7_0_100M_0/zynq_axi_gpio_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_axi_gpio_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_axi_gpio/ip/zynq_axi_gpio_axi_gpio_1_0/zynq_axi_gpio_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_axi_gpio_1_0 || ORIG_REF_NAME==zynq_axi_gpio_axi_gpio_1_0} -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/zed_nand_axi_gpio/zed_nand_axi_gpio.gen/sources_1/bd/zynq_axi_gpio/zynq_axi_gpio_ooc.xdc
