set_property SRC_FILE_INFO {cfile:/home/carbon/kambadur/Projects/Vivado/cmods7_and_axi_gpio/cmods7_and_axi_gpio.srcs/constrs_1/new/cmods7.xdc rfile:../../../cmods7_and_axi_gpio.srcs/constrs_1/new/cmods7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports btn1]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports reset]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D2 [get_ports btn0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E2    IOSTANDARD LVCMOS33 } [get_ports led0]
