# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/carbon/kambadur/Projects/Vivado/mb_uart/mb_uart.srcs/sources_1/bd/mb_uart/ip/mb_uart_dlmb_bram_if_cntlr_0/mb_uart_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_uart_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/carbon/kambadur/Projects/Vivado/mb_uart/mb_uart.gen/sources_1/bd/mb_uart/ip/mb_uart_dlmb_bram_if_cntlr_0/mb_uart_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_uart_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/carbon/kambadur/Projects/Vivado/mb_uart/mb_uart.srcs/sources_1/bd/mb_uart/ip/mb_uart_dlmb_bram_if_cntlr_0/mb_uart_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'mb_uart_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/carbon/kambadur/Projects/Vivado/mb_uart/mb_uart.gen/sources_1/bd/mb_uart/ip/mb_uart_dlmb_bram_if_cntlr_0/mb_uart_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_uart_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
