domain_path: /home/carbon/kambadur/Projects/Vivado/zynq_bram_1/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
