set_property SRC_FILE_INFO {cfile:/home/carbon/kambadur/Projects/Vivado/custom_axi_lite_slv_1/custom_axi_lite_slv_1.srcs/constrs_1/new/debugsignals.xdc rfile:../../../custom_axi_lite_slv_1.srcs/constrs_1/new/debugsignals.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/myip_fa_0/s00_axi_wstrb[0]} {design_1_i/myip_fa_0/s00_axi_wstrb[1]} {design_1_i/myip_fa_0/s00_axi_wstrb[2]} {design_1_i/myip_fa_0/s00_axi_wstrb[3]}]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/myip_fa_0/s00_axi_araddr[2]} {design_1_i/myip_fa_0/s00_axi_araddr[3]}]]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/myip_fa_0/s00_axi_rdata[0]} {design_1_i/myip_fa_0/s00_axi_rdata[1]} {design_1_i/myip_fa_0/s00_axi_rdata[2]} {design_1_i/myip_fa_0/s00_axi_rdata[3]} {design_1_i/myip_fa_0/s00_axi_rdata[4]} {design_1_i/myip_fa_0/s00_axi_rdata[5]} {design_1_i/myip_fa_0/s00_axi_rdata[6]} {design_1_i/myip_fa_0/s00_axi_rdata[7]} {design_1_i/myip_fa_0/s00_axi_rdata[8]} {design_1_i/myip_fa_0/s00_axi_rdata[9]} {design_1_i/myip_fa_0/s00_axi_rdata[10]} {design_1_i/myip_fa_0/s00_axi_rdata[11]} {design_1_i/myip_fa_0/s00_axi_rdata[12]} {design_1_i/myip_fa_0/s00_axi_rdata[13]} {design_1_i/myip_fa_0/s00_axi_rdata[14]} {design_1_i/myip_fa_0/s00_axi_rdata[15]} {design_1_i/myip_fa_0/s00_axi_rdata[16]} {design_1_i/myip_fa_0/s00_axi_rdata[17]} {design_1_i/myip_fa_0/s00_axi_rdata[18]} {design_1_i/myip_fa_0/s00_axi_rdata[19]} {design_1_i/myip_fa_0/s00_axi_rdata[20]} {design_1_i/myip_fa_0/s00_axi_rdata[21]} {design_1_i/myip_fa_0/s00_axi_rdata[22]} {design_1_i/myip_fa_0/s00_axi_rdata[23]} {design_1_i/myip_fa_0/s00_axi_rdata[24]} {design_1_i/myip_fa_0/s00_axi_rdata[25]} {design_1_i/myip_fa_0/s00_axi_rdata[26]} {design_1_i/myip_fa_0/s00_axi_rdata[27]} {design_1_i/myip_fa_0/s00_axi_rdata[28]} {design_1_i/myip_fa_0/s00_axi_rdata[29]} {design_1_i/myip_fa_0/s00_axi_rdata[30]} {design_1_i/myip_fa_0/s00_axi_rdata[31]}]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/myip_fa_0/s00_axi_wdata[0]} {design_1_i/myip_fa_0/s00_axi_wdata[1]} {design_1_i/myip_fa_0/s00_axi_wdata[2]} {design_1_i/myip_fa_0/s00_axi_wdata[3]} {design_1_i/myip_fa_0/s00_axi_wdata[4]} {design_1_i/myip_fa_0/s00_axi_wdata[5]} {design_1_i/myip_fa_0/s00_axi_wdata[6]} {design_1_i/myip_fa_0/s00_axi_wdata[7]} {design_1_i/myip_fa_0/s00_axi_wdata[8]} {design_1_i/myip_fa_0/s00_axi_wdata[9]} {design_1_i/myip_fa_0/s00_axi_wdata[10]} {design_1_i/myip_fa_0/s00_axi_wdata[11]} {design_1_i/myip_fa_0/s00_axi_wdata[12]} {design_1_i/myip_fa_0/s00_axi_wdata[13]} {design_1_i/myip_fa_0/s00_axi_wdata[14]} {design_1_i/myip_fa_0/s00_axi_wdata[15]} {design_1_i/myip_fa_0/s00_axi_wdata[16]} {design_1_i/myip_fa_0/s00_axi_wdata[17]} {design_1_i/myip_fa_0/s00_axi_wdata[18]} {design_1_i/myip_fa_0/s00_axi_wdata[19]} {design_1_i/myip_fa_0/s00_axi_wdata[20]} {design_1_i/myip_fa_0/s00_axi_wdata[21]} {design_1_i/myip_fa_0/s00_axi_wdata[22]} {design_1_i/myip_fa_0/s00_axi_wdata[23]} {design_1_i/myip_fa_0/s00_axi_wdata[24]} {design_1_i/myip_fa_0/s00_axi_wdata[25]} {design_1_i/myip_fa_0/s00_axi_wdata[26]} {design_1_i/myip_fa_0/s00_axi_wdata[27]} {design_1_i/myip_fa_0/s00_axi_wdata[28]} {design_1_i/myip_fa_0/s00_axi_wdata[29]} {design_1_i/myip_fa_0/s00_axi_wdata[30]} {design_1_i/myip_fa_0/s00_axi_wdata[31]}]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/myip_fa_0/s00_axi_awaddr[2]} {design_1_i/myip_fa_0/s00_axi_awaddr[3]}]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/myip_fa_0/s00_axi_arready]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/myip_fa_0/s00_axi_arvalid]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/myip_fa_0/s00_axi_awready]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/myip_fa_0/s00_axi_awvalid]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/myip_fa_0/s00_axi_bready]]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/myip_fa_0/s00_axi_bvalid]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/myip_fa_0/s00_axi_rready]]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/myip_fa_0/s00_axi_rvalid]]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/myip_fa_0/s00_axi_wready]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/myip_fa_0/s00_axi_wvalid]]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_awaddr[3]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_araddr[2]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[10]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[9]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[5]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_araddr[3]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[5]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[7]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[10]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[9]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[1]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[2]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[21]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[12]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[11]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[14]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[17]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[22]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[31]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[25]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[27]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[1]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[2]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[23]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[15]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[30]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[26]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[21]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[23]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[3]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[12]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[28]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[0]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[18]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[14]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[15]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[16]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_awaddr[2]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[8]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[6]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[7]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[4]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[0]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[4]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[6]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[8]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[3]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[17]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[13]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[30]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[20]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[24]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wstrb[2]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[19]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[20]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[26]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[28]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[16]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[24]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[25]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[22]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[29]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[29]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[11]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wstrb[0]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wstrb[3]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_rdata[19]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wstrb[1]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[31]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[18]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[27]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/myip_fa_0/s00_axi_wdata[13]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_arready]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_arvalid]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_awready]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_awvalid]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_bready]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_bvalid]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_rready]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_rvalid]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_wready]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/myip_fa_0/s00_axi_wvalid]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
