# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/design_1_axi_smc_1_2.xci
# IP: The module: 'design_1_axi_smc_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/bd_69f9.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_0/bd_69f9_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_1/bd_69f9_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_2/bd_69f9_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_3/bd_69f9_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_4/bd_69f9_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_5/bd_69f9_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_6/bd_69f9_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_7/bd_69f9_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_8/bd_69f9_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_9/bd_69f9_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_10/bd_69f9_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_11/bd_69f9_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_12/bd_69f9_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_1/bd_69f9_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_1/bd_69f9_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_5/bd_69f9_s00a2s_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_6/bd_69f9_sarn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_7/bd_69f9_srn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_8/bd_69f9_sawn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_9/bd_69f9_swn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_10/bd_69f9_sbn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_11/bd_69f9_m00s2a_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/design_1_axi_smc_1_2.xci
# IP: The module: 'design_1_axi_smc_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/bd_69f9.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_0/bd_69f9_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_1/bd_69f9_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_2/bd_69f9_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_3/bd_69f9_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_4/bd_69f9_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_5/bd_69f9_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_6/bd_69f9_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_7/bd_69f9_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_8/bd_69f9_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_9/bd_69f9_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_10/bd_69f9_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_11/bd_69f9_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_12/bd_69f9_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_1/bd_69f9_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_1/bd_69f9_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_5/bd_69f9_s00a2s_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_6/bd_69f9_sarn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_7/bd_69f9_srn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_8/bd_69f9_sawn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_9/bd_69f9_swn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_10/bd_69f9_sbn_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/bd_0/ip/ip_11/bd_69f9_m00s2a_0_ooc.xdc

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/zynq_bram/zynq_bram.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
