set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_ARLEN[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_ARVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_AWVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_BREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_RREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_WLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_WVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_ARREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_AWREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_BRESP[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_BRESP[0]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_BVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_RLAST]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_RRESP[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_smc_1_M00_AXI_RRESP[0]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_RVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axi_smc_1_M00_AXI_WREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[1]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[0]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[1]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[2]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_WE[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_smc_1_M00_AXI_BRESP[0]} {design_1_i/axi_smc_1_M00_AXI_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 13 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[0]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[1]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[2]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[3]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[4]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[5]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[6]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[7]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[8]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[9]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[10]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[11]} {design_1_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axi_smc_1_M00_AXI_RRESP[0]} {design_1_i/axi_smc_1_M00_AXI_RRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/axi_smc_1_M00_AXI_ARLEN[0]} {design_1_i/axi_smc_1_M00_AXI_ARLEN[1]} {design_1_i/axi_smc_1_M00_AXI_ARLEN[2]} {design_1_i/axi_smc_1_M00_AXI_ARLEN[3]} {design_1_i/axi_smc_1_M00_AXI_ARLEN[4]} {design_1_i/axi_smc_1_M00_AXI_ARLEN[5]} {design_1_i/axi_smc_1_M00_AXI_ARLEN[6]} {design_1_i/axi_smc_1_M00_AXI_ARLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axi_smc_1_M00_AXI_ARREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axi_smc_1_M00_AXI_ARVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axi_smc_1_M00_AXI_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axi_smc_1_M00_AXI_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axi_smc_1_M00_AXI_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/axi_smc_1_M00_AXI_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/axi_smc_1_M00_AXI_RLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/axi_smc_1_M00_AXI_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/axi_smc_1_M00_AXI_RVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/axi_smc_1_M00_AXI_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/axi_smc_1_M00_AXI_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/axi_smc_1_M00_AXI_WVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
