domain_path: /home/carbon/kambadur/Projects/Vivado/project_2/platform_zynq_spi_intr/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
