domain_path: /home/carbon/kambadur/Projects/Vivado/mb_axi_gpio/platform/export/platform/sw/standalone_microblaze_0
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
