# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys4.xdc

# Block Designs: bd/mb_uart/mb_uart.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart || ORIG_REF_NAME==mb_uart} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_microblaze_0_0/mb_uart_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_microblaze_0_0 || ORIG_REF_NAME==mb_uart_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_dlmb_v10_0/mb_uart_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_dlmb_v10_0 || ORIG_REF_NAME==mb_uart_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_ilmb_v10_0/mb_uart_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_ilmb_v10_0 || ORIG_REF_NAME==mb_uart_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_dlmb_bram_if_cntlr_0/mb_uart_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_uart_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_ilmb_bram_if_cntlr_0/mb_uart_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_uart_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_lmb_bram_0/mb_uart_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_lmb_bram_0 || ORIG_REF_NAME==mb_uart_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_mdm_1_0/mb_uart_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_mdm_1_0 || ORIG_REF_NAME==mb_uart_mdm_1_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_clk_wiz_1_0/mb_uart_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_clk_wiz_1_0 || ORIG_REF_NAME==mb_uart_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_rst_clk_wiz_1_100M_0/mb_uart_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_uart_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_reset_inv_0_0/mb_uart_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_reset_inv_0_0 || ORIG_REF_NAME==mb_uart_reset_inv_0_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_axi_uartlite_0_0/mb_uart_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_axi_uartlite_0_0 || ORIG_REF_NAME==mb_uart_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_uart/ip/mb_uart_axi_smc_0/mb_uart_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_uart_axi_smc_0 || ORIG_REF_NAME==mb_uart_axi_smc_0} -quiet] -quiet

# XDC: /home/carbon/kambadur/Projects/Vivado/mb_uart/mb_uart.gen/sources_1/bd/mb_uart/mb_uart_ooc.xdc
